// Generated by gencpp from file my_messages/named_point.msg
// DO NOT EDIT!


#ifndef MY_MESSAGES_MESSAGE_NAMED_POINT_H
#define MY_MESSAGES_MESSAGE_NAMED_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_messages
{
template <class ContainerAllocator>
struct named_point_
{
  typedef named_point_<ContainerAllocator> Type;

  named_point_()
    : nome_del_punto()
    , x(0)
    , y(0)
    , z(0)  {
    }
  named_point_(const ContainerAllocator& _alloc)
    : nome_del_punto(_alloc)
    , x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _nome_del_punto_type;
  _nome_del_punto_type nome_del_punto;

   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::my_messages::named_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_messages::named_point_<ContainerAllocator> const> ConstPtr;

}; // struct named_point_

typedef ::my_messages::named_point_<std::allocator<void> > named_point;

typedef boost::shared_ptr< ::my_messages::named_point > named_pointPtr;
typedef boost::shared_ptr< ::my_messages::named_point const> named_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_messages::named_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_messages::named_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_messages::named_point_<ContainerAllocator1> & lhs, const ::my_messages::named_point_<ContainerAllocator2> & rhs)
{
  return lhs.nome_del_punto == rhs.nome_del_punto &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_messages::named_point_<ContainerAllocator1> & lhs, const ::my_messages::named_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_messages::named_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_messages::named_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_messages::named_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_messages::named_point_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_messages::named_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_messages::named_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_messages::named_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec20b1e298fa17ae0670f4a8348f6341";
  }

  static const char* value(const ::my_messages::named_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec20b1e298fa17aeULL;
  static const uint64_t static_value2 = 0x0670f4a8348f6341ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_messages::named_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_messages/named_point";
  }

  static const char* value(const ::my_messages::named_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_messages::named_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string nome_del_punto\n"
"int64 x\n"
"int64 y\n"
"int64 z\n"
;
  }

  static const char* value(const ::my_messages::named_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_messages::named_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nome_del_punto);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct named_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_messages::named_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_messages::named_point_<ContainerAllocator>& v)
  {
    s << indent << "nome_del_punto: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.nome_del_punto);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MESSAGES_MESSAGE_NAMED_POINT_H
